### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by nirvdrum** [SamSaffron/fast_blank#22]
I've noticed none of the releases are tagged. There's not a ton of activity in the repo, so finding the right commit isn't too hard. But there's also only three releases pushed to RubyGems, so I hope backfilling tags isn't too onerous.

**Comment by SamSaffron** [comment]
Happy to tag going forward, and if you can find the commit hashes I am happy to backfill

**Comment by nirvdrum** [comment]
As far as I can tell, these are the correct revisions:

0.0.1: 5d63f521b228fe9aa386ed8b8bff280781b23004
0.0.2: 3cc0e282acc2ee5c0f3927818ed83ca6bbb7acec
1.0.0: 80510936207f4b44a5e8bbc2db5566f37746f686

**Comment by SamSaffron** [comment]
thanks! cool this is done now.
