### ISSUE TITLE
Add support for Object#blank?

### ISSUE THREAD

**Issue by envygeeks** [SamSaffron/fast_blank#23]
It would be nice if this library provided `Object#blank?` so that it can be used outside of Rails, where it would really shine... I'm happy to send a patch to support it, if this is accepted.

**Comment by SamSaffron** [comment]
I am a bit uneasy about adding this, Matz does not want a blank interface and not even a string blank ... https://bugs.ruby-lang.org/issues/12306 I feel odd trying to swim upstream here.

**Comment by envygeeks** [comment]
Unless this is in stdlib I don't see how that would affect.this library?

**Comment by SamSaffron** [comment]
This lib is very super specific about providing a "fast" implementation for String blank defined by AS. I just don't want to get into the business of monkey patching other core classes out-of-the-box. The list is just too big... 

Queue.new.blank? 
null.blank?
[].blank?
Set.new.blank?
0.blank?
{}.blank? 

I don't want to carry all this code here.

**Comment by envygeeks** [comment]
Why would you need to carry all that code?

```ruby
class Object
  def blank?
    nil? || (respond_to?(:empty?) && empty?)
  end
end
```

Is all you need.

**Comment by SamSaffron** [comment]
That is not efficient cause you end up calling respond_to for every call. `self&.empty?` may be fast enough. It will still be slower than direct patching. 

Sadly all my `fast_` gems require that the implementation be the absolute fastest possible. 

I just don't feel this is in scope here.

**Comment by envygeeks** [comment]
I'll be back in the morning.
